project:
  type: website



website:

  favicon: images/ai5.png
  title: "Data Science Stretch"
  navbar:
    background: primary
    search: true
    left:
      - text: Welcome
        file: welcome.qmd
      # margin-header: |
        # ![ai](/images/porter_small.png)

  sidebar:
    contents: articles/*


format:
  html:
    theme: darkly
    css: styles.css
    toc: true

