project:
  type: website



website:

  favicon: images/ai5.png
  title: "Data Science Stretch"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.qmd
      - about.qmd
      # margin-header: |
        # ![ai](/images/porter_small.png)

  sidebar:
    contents: articles/math/*
    # contents: articles/*
    # style: "docked"
    # search: true
    # title: "Feedforward Neural Network"
    # contents:
    # - text: "Feedforward Neural Network"
      # file: articles/Feedforward Neural Network.qmd
    #   contents:
      # - section: "Math"


format:
  html:
    theme: darkly
    css: styles.css
    toc: true

